// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: proto/sheep.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBoolFlagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key            string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ConsistencyKey string `protobuf:"bytes,2,opt,name=consistency_key,json=consistencyKey,proto3" json:"consistency_key,omitempty"`
}

func (x *GetBoolFlagRequest) Reset() {
	*x = GetBoolFlagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sheep_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBoolFlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoolFlagRequest) ProtoMessage() {}

func (x *GetBoolFlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sheep_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoolFlagRequest.ProtoReflect.Descriptor instead.
func (*GetBoolFlagRequest) Descriptor() ([]byte, []int) {
	return file_proto_sheep_proto_rawDescGZIP(), []int{0}
}

func (x *GetBoolFlagRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetBoolFlagRequest) GetConsistencyKey() string {
	if x != nil {
		return x.ConsistencyKey
	}
	return ""
}

type GetBoolFlagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value bool   `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetBoolFlagResponse) Reset() {
	*x = GetBoolFlagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sheep_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBoolFlagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoolFlagResponse) ProtoMessage() {}

func (x *GetBoolFlagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sheep_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoolFlagResponse.ProtoReflect.Descriptor instead.
func (*GetBoolFlagResponse) Descriptor() ([]byte, []int) {
	return file_proto_sheep_proto_rawDescGZIP(), []int{1}
}

func (x *GetBoolFlagResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetBoolFlagResponse) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type CreateFlagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *CreateFlagRequest) Reset() {
	*x = CreateFlagRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sheep_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFlagRequest) ProtoMessage() {}

func (x *CreateFlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sheep_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFlagRequest.ProtoReflect.Descriptor instead.
func (*CreateFlagRequest) Descriptor() ([]byte, []int) {
	return file_proto_sheep_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFlagRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type CreateFlagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *CreateFlagResponse) Reset() {
	*x = CreateFlagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sheep_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFlagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFlagResponse) ProtoMessage() {}

func (x *CreateFlagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sheep_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFlagResponse.ProtoReflect.Descriptor instead.
func (*CreateFlagResponse) Descriptor() ([]byte, []int) {
	return file_proto_sheep_proto_rawDescGZIP(), []int{3}
}

func (x *CreateFlagResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_proto_sheep_proto protoreflect.FileDescriptor

var file_proto_sheep_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x68, 0x65, 0x65, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x68, 0x65, 0x65, 0x70, 0x22, 0x4f, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x42, 0x6f, 0x6f, 0x6c, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x63,
	0x79, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e,
	0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x4b, 0x65, 0x79, 0x22, 0x3d, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6c, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x25, 0x0a, 0x11, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x22, 0x26, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x32, 0x90, 0x01, 0x0a, 0x05, 0x53, 0x68,
	0x65, 0x65, 0x70, 0x12, 0x44, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6c, 0x46, 0x6c,
	0x61, 0x67, 0x12, 0x19, 0x2e, 0x73, 0x68, 0x65, 0x65, 0x70, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f,
	0x6f, 0x6c, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x73, 0x68, 0x65, 0x65, 0x70, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6c, 0x46, 0x6c, 0x61,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0a, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x18, 0x2e, 0x73, 0x68, 0x65, 0x65, 0x70, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x19, 0x2e, 0x73, 0x68, 0x65, 0x65, 0x70, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0a, 0x5a, 0x08,
	0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_sheep_proto_rawDescOnce sync.Once
	file_proto_sheep_proto_rawDescData = file_proto_sheep_proto_rawDesc
)

func file_proto_sheep_proto_rawDescGZIP() []byte {
	file_proto_sheep_proto_rawDescOnce.Do(func() {
		file_proto_sheep_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_sheep_proto_rawDescData)
	})
	return file_proto_sheep_proto_rawDescData
}

var file_proto_sheep_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_sheep_proto_goTypes = []interface{}{
	(*GetBoolFlagRequest)(nil),  // 0: sheep.GetBoolFlagRequest
	(*GetBoolFlagResponse)(nil), // 1: sheep.GetBoolFlagResponse
	(*CreateFlagRequest)(nil),   // 2: sheep.CreateFlagRequest
	(*CreateFlagResponse)(nil),  // 3: sheep.CreateFlagResponse
}
var file_proto_sheep_proto_depIdxs = []int32{
	0, // 0: sheep.Sheep.GetBoolFlag:input_type -> sheep.GetBoolFlagRequest
	2, // 1: sheep.Sheep.CreateFlag:input_type -> sheep.CreateFlagRequest
	1, // 2: sheep.Sheep.GetBoolFlag:output_type -> sheep.GetBoolFlagResponse
	3, // 3: sheep.Sheep.CreateFlag:output_type -> sheep.CreateFlagResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sheep_proto_init() }
func file_proto_sheep_proto_init() {
	if File_proto_sheep_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_sheep_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBoolFlagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sheep_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBoolFlagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sheep_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFlagRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sheep_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFlagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_sheep_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sheep_proto_goTypes,
		DependencyIndexes: file_proto_sheep_proto_depIdxs,
		MessageInfos:      file_proto_sheep_proto_msgTypes,
	}.Build()
	File_proto_sheep_proto = out.File
	file_proto_sheep_proto_rawDesc = nil
	file_proto_sheep_proto_goTypes = nil
	file_proto_sheep_proto_depIdxs = nil
}
